# uv run python delete_me/replay/main.py --case stress --frames 1000000
# Made by Codex as a disposable replay integration runner.

"""Exercise replay persistence through selectable integration cases."""

import asyncio
import sys
from dataclasses import dataclass, field, replace
from hashlib import sha256
from pathlib import Path
from time import perf_counter
from typing import cast

from cli_fw import Command, arg
from pacman.maze_loader import Solver, load_maze
from pacman.replay.maze_codec import encode_collectibles, encode_topology
from pacman.replay.models import (
    Collectible,
    CollectibleChange,
    Coord,
    Direction,
    EncodedMaze,
    Frame,
    FrameBatch,
    GamePhase,
    Ghost,
    GhostFrame,
    GhostState,
    PlayerFrame,
    Position,
    ReplayId,
    Score,
    Tick,
    TileIndex,
)
from pacman.replay.recorder import Recorder
from pacman.replay.store import ReplayStore
from pacman.replay.writer import ReplayWriter, WriterCommand
from typed_concurrency import Channel, Group
from typed_errs import Err, Some

DB_PATH = Path("/tmp/pacman-replay-test.sqlite3")
CASES = ["all", "maze", "metadata", "frames", "simulate", "stress", "death"]
DEATH_SCENARIOS = [
    "head-on",
    "from-behind",
    "turned-into",
    "frightened",
    "near-miss",
    "insufficient-history",
]


@dataclass
class ReplayArgs:
    """Arguments accepted by the disposable replay runner."""

    case: str = cast(
        str,
        arg(default="all", choices=CASES, help="Replay exercise to run"),
    )
    frames: int = cast(
        int,
        arg(default=1_000_000, help="Frames written by the stress case"),
    )
    batch_size: int = cast(
        int,
        arg(default=10_000, help="Frames per SQLite transaction"),
    )
    keep_db: bool = cast(
        bool,
        arg(default=False, help="Keep the generated database for inspection"),
    )
    ticks: int = cast(
        int,
        arg(default=500, help="Frames generated by the simulated game"),
    )
    buffer_size: int = cast(
        int,
        arg(default=64, help="Recorder frames per dispatched batch"),
    )
    width: int = cast(int, arg(default=21, help="Simulated maze width"))
    height: int = cast(int, arg(default=21, help="Simulated maze height"))
    seed: int = cast(int, arg(default=42, help="Simulated maze seed"))
    scenario: str = cast(
        str,
        arg(
            default="head-on",
            choices=DEATH_SCENARIOS,
            help="Synthetic death scenario generated by the death case",
        ),
    )


@dataclass(slots=True)
class DeathScenario:
    """Build short semantic replay sequences without a game or renderer."""

    replay_id: ReplayId
    tick: int = 100
    lives: int = 3
    _player: PlayerFrame = field(
        default_factory=lambda: PlayerFrame(Position(Coord(0), Coord(0)), Direction.RIGHT)
    )
    _ghosts: dict[Ghost, GhostFrame] = field(default_factory=dict)
    _frames: list[Frame] = field(default_factory=list)

    def pacman(
        self,
        position: tuple[int, int],
        moving: Direction = Direction.RIGHT,
    ) -> "DeathScenario":
        """Place Pac-Man and select his movement direction.

        Returns:
            This scenario for fluent composition.
        """
        self._player = PlayerFrame(Position(Coord(position[0]), Coord(position[1])), moving)
        return self

    def ghost(
        self,
        ghost: Ghost,
        position: tuple[int, int],
        *,
        moving: Direction = Direction.LEFT,
        state: GhostState = GhostState.CHASE,
    ) -> "DeathScenario":
        """Place or replace one ghost in the scenario.

        Returns:
            This scenario for fluent composition.
        """
        self._ghosts[ghost] = GhostFrame(
            ghost,
            Position(Coord(position[0]), Coord(position[1])),
            moving,
            state,
        )
        return self

    def turn(self, direction: Direction) -> "DeathScenario":
        """Change Pac-Man's direction without moving him.

        Returns:
            This scenario for fluent composition.
        """
        self._player = replace(self._player, direction=direction)
        return self

    def advance(self, steps: int = 1) -> "DeathScenario":
        """Record the initial state, then move every actor by whole tiles.

        Returns:
            This scenario for fluent composition.
        """
        if not self._frames:
            self._record(GamePhase.PLAYING)
        for _ in range(steps):
            self.tick += 1
            self._player = replace(
                self._player,
                position=_move(self._player.position, self._player.direction),
            )
            self._ghosts = {
                ghost: replace(
                    frame,
                    position=_move(frame.position, frame.direction),
                )
                for ghost, frame in self._ghosts.items()
            }
            self._record(GamePhase.PLAYING)
        return self

    def die(self) -> "DeathScenario":
        """Append the explicit death transition at the current positions.

        Returns:
            This scenario for fluent composition.
        """
        if not self._frames:
            self._record(GamePhase.PLAYING)
        self.tick += 1
        self._record(GamePhase.DYING)
        return self

    def collide_with(self, ghost: Ghost) -> "DeathScenario":
        """Append a collision frame with the selected ghost as the contact.

        Returns:
            This scenario for fluent composition.
        """
        if not self._frames:
            self._record(GamePhase.PLAYING)
        self.tick += 1
        self._ghosts[ghost] = replace(self._ghosts[ghost], position=self._player.position)
        self._record(GamePhase.PLAYING)
        return self

    def batch(self) -> FrameBatch:
        """Return the generated sequence through the analyzer's real boundary."""
        return FrameBatch(self.replay_id, tuple(self._frames), ())

    def _record(self, phase: GamePhase) -> None:
        self._frames.append(
            Frame(
                Tick(self.tick),
                self._player,
                tuple(self._ghosts[ghost] for ghost in sorted(self._ghosts)),
                Score(0),
                self.lives,
                phase,
            )
        )


def _move(position: Position, direction: Direction) -> Position:
    """Move a replay position one tile in a cardinal direction.

    Returns:
        The adjacent replay position.
    """
    dx, dy = {
        Direction.UP: (0, -1),
        Direction.RIGHT: (1, 0),
        Direction.DOWN: (0, 1),
        Direction.LEFT: (-1, 0),
    }[direction]
    return Position(Coord(int(position.x) + dx), Coord(int(position.y) + dy))


def death_scenario(name: str, replay_id: ReplayId) -> FrameBatch:
    """Generate one named analyzer input as an ordinary replay batch.

    Returns:
        Frames ready for persistence or direct analysis.

    Raises:
        ValueError: If the scenario name is unknown.
    """
    scenario = DeathScenario(replay_id)

    if name == "head-on":
        _ = scenario.pacman((10, 10)).ghost(Ghost.BLINKY, (14, 10)).advance(2).die()
    elif name == "from-behind":
        _ = (
            scenario
            .pacman((10, 10))
            .ghost(Ghost.BLINKY, (8, 10), moving=Direction.RIGHT)
            .advance()
            .collide_with(Ghost.BLINKY)
            .die()
        )
    elif name == "turned-into":
        _ = (
            scenario
            .pacman((10, 10), Direction.UP)
            .ghost(Ghost.PINKY, (11, 9), moving=Direction.DOWN)
            .advance()
            .turn(Direction.RIGHT)
            .collide_with(Ghost.PINKY)
            .die()
        )
    elif name == "frightened":
        _ = (
            scenario
            .pacman((10, 10))
            .ghost(Ghost.INKY, (14, 10), state=GhostState.FRIGHTENED)
            .advance(2)
        )
    elif name == "near-miss":
        _ = scenario.pacman((10, 10)).ghost(Ghost.CLYDE, (12, 11), moving=Direction.LEFT).advance(2)
    elif name == "insufficient-history":
        _ = scenario.pacman((12, 10)).ghost(Ghost.BLINKY, (12, 10)).die()
    else:
        raise ValueError(f"unknown death scenario: {name}")

    return scenario.batch()


def replay_frame(tick: int, four_ghosts: bool = True) -> Frame:
    """Build a deterministic frame for integration testing.

    Args:
        tick: Simulation tick stored in the frame.
        four_ghosts: Whether to include every ghost or only Blinky.

    Returns:
        A representative replay frame.
    """
    ghosts = (
        GhostFrame(
            ghost=Ghost.BLINKY,
            position=Position(x=Coord(1), y=Coord(1)),
            direction=Direction.LEFT,
            state=GhostState.CHASE,
        ),
        GhostFrame(
            ghost=Ghost.PINKY,
            position=Position(x=Coord(1), y=Coord(0)),
            direction=Direction.DOWN,
            state=GhostState.SCATTER,
        ),
        GhostFrame(
            ghost=Ghost.INKY,
            position=Position(x=Coord(0), y=Coord(1)),
            direction=Direction.UP,
            state=GhostState.FRIGHTENED,
        ),
        GhostFrame(
            ghost=Ghost.CLYDE,
            position=Position(x=Coord(1), y=Coord(1)),
            direction=Direction.RIGHT,
            state=GhostState.EATEN,
        ),
    )
    return Frame(
        tick=Tick(tick),
        player=PlayerFrame(
            position=Position(x=Coord(tick % 2), y=Coord((tick // 2) % 2)),
            direction=Direction(tick % 4),
        ),
        ghosts=ghosts if four_ghosts else ghosts[:1],
        score=Score(tick * 10),
        lives=3,
        phase=GamePhase.PLAYING,
    )


def database_size(path: Path) -> int:
    """Return the combined SQLite database, WAL, and shared-memory size."""
    paths = (path, Path(f"{path}-wal"), Path(f"{path}-shm"))
    return sum(candidate.stat().st_size for candidate in paths if candidate.exists())


def remove_database(path: Path) -> None:
    """Remove a SQLite database and its temporary sidecar files."""
    for candidate in (path, Path(f"{path}-wal"), Path(f"{path}-shm")):
        candidate.unlink(missing_ok=True)


def stress(store: ReplayStore, replay_id: ReplayId, args: ReplayArgs) -> int:
    """Write and verify a large replay while reporting storage costs.

    Args:
        store: Initialized replay store.
        replay_id: Replay receiving generated frames.
        args: Stress-test controls.

    Returns:
        Zero after a successful write and verification.
    """
    if args.frames <= 0 or args.batch_size <= 0:
        print("frames and batch-size must both be greater than zero")
        return 2

    started = perf_counter()
    for offset in range(0, args.frames, args.batch_size):
        stop = min(offset + args.batch_size, args.frames)
        frames = tuple(replay_frame(tick, four_ghosts=False) for tick in range(offset, stop))
        store.append(FrameBatch(replay_id, frames, ())).unwrap()

    elapsed = perf_counter() - started
    for tick in (0, args.frames // 2, args.frames - 1):
        assert store.frame(replay_id, Tick(tick)).unwrap() == replay_frame(tick, four_ghosts=False)

    size = database_size(DB_PATH)
    print("\n== stress results ==")
    print(f"frames:       {args.frames:,}")
    print(f"elapsed:      {elapsed:.2f} s")
    print(f"throughput:   {args.frames / elapsed:,.0f} frames/s")
    print(f"database:     {size / 1_048_576:.2f} MiB")
    print(f"bytes/frame:  {size / args.frames:.1f}")
    print("verified:     first, middle, last")
    return 0


def direction_between(current: tuple[int, int], following: tuple[int, int]) -> Direction:
    """Return the replay direction between adjacent maze positions."""
    delta = (following[0] - current[0], following[1] - current[1])
    return {
        (0, -1): Direction.UP,
        (1, 0): Direction.RIGHT,
        (0, 1): Direction.DOWN,
        (-1, 0): Direction.LEFT,
    }[delta]


def route_direction(route: list[tuple[int, int]], index: int, step: int = 1) -> Direction:
    """Return an actor's direction along a cyclic maze route.

    Returns:
        The direction from the indexed tile to its adjacent destination.
    """
    return direction_between(route[index % len(route)], route[(index + step) % len(route)])


def simulated_history(
    replay_id: ReplayId,
    route: list[tuple[int, int]],
    ticks: int,
) -> FrameBatch:
    """Generate a deterministic multi-ghost fake game history.

    Blinky closes on Pac-Man, Pinky moves ahead of him, Inky traverses the
    route backwards, and Clyde patrols slowly. The middle of the history
    includes frightened and eaten state transitions. Blinky makes contact on
    the penultimate tick and the final frame enters ``DYING``.

    Returns:
        A replay batch suitable for direct analysis or persistence.
    """
    frames: list[Frame] = []
    route_size = len(route)
    frightened_start = ticks // 3
    frightened_stop = min(frightened_start + 5, ticks - 3)
    eaten_stop = min(frightened_stop + 4, ticks - 2)

    for tick in range(ticks):
        pac_index = (tick // 2) % route_size
        pac_position = route[pac_index]
        phase = GamePhase.DYING if tick == ticks - 1 else GamePhase.PLAYING

        ghost_specs = (
            (Ghost.BLINKY, (tick + route_size // 3) % route_size, 1),
            (Ghost.PINKY, (pac_index + 4) % route_size, 1),
            (Ghost.INKY, (route_size // 2 - tick // 2) % route_size, -1),
            (Ghost.CLYDE, (route_size - 2 - tick // 3) % route_size, -1),
        )
        ghosts: list[GhostFrame] = []

        for ghost, route_index, step in ghost_specs:
            state = GhostState.CHASE
            if frightened_start <= tick < frightened_stop:
                state = GhostState.FRIGHTENED
            elif ghost is Ghost.INKY and frightened_stop <= tick < eaten_stop:
                state = GhostState.EATEN

            if ghost is Ghost.BLINKY and tick >= ticks - 2:
                ghost_position = pac_position
                direction = route_direction(route, pac_index)
                state = GhostState.CHASE
            else:
                ghost_position = route[route_index]
                if ghost_position == pac_position:
                    route_index = (route_index + step) % route_size
                    ghost_position = route[route_index]
                direction = route_direction(route, route_index, step)

            ghosts.append(
                GhostFrame(
                    ghost,
                    Position(Coord(ghost_position[0]), Coord(ghost_position[1])),
                    direction,
                    state,
                )
            )

        frames.append(
            Frame(
                Tick(tick),
                PlayerFrame(
                    Position(Coord(pac_position[0]), Coord(pac_position[1])),
                    route_direction(route, pac_index),
                ),
                tuple(ghosts),
                Score(tick * 10),
                2 if phase is GamePhase.DYING else 3,
                phase,
            )
        )

    return FrameBatch(replay_id, tuple(frames), ())


async def simulate_game(store: ReplayStore, args: ReplayArgs) -> int:
    """Generate a maze and persist a synthetic game through recorder and writer.

    Returns:
        Zero after persistence and reconstruction succeed.
    """
    if args.ticks < 8 or args.buffer_size <= 0:
        print("ticks must be at least eight and buffer-size must be greater than zero")
        return 2

    maze = load_maze(args.width, args.height, Some(args.seed)).unwrap()
    path = maze.path(maze.entry, maze.exit, Solver.BFS).unwrap()
    route = path + path[-2:0:-1]
    topology = encode_topology(maze.cells).unwrap()
    collectibles = [Collectible.PACGUM] * (maze.width * maze.height)
    entry_tile = maze.entry[1] * maze.width + maze.entry[0]
    collectibles[entry_tile] = Collectible.NONE
    initial_collectibles = encode_collectibles(collectibles).unwrap()
    maze_id = store.create_maze(
        EncodedMaze(
            width=maze.width,
            height=maze.height,
            entry=maze.entry,
            exit=maze.exit,
            topology=topology,
            initial_collectibles=initial_collectibles,
            checksum=sha256(topology + initial_collectibles).digest(),
        )
    ).unwrap()
    replay_id = store.create_replay(
        maze_id=maze_id,
        tick_hz=60,
        level=1,
        simulation_version=1,
        config_hash=b"synthetic-game",
        rng_seed=args.seed,
    ).unwrap()

    channel = Channel[WriterCommand](4)
    writer = ReplayWriter(store, channel)
    recorder = Recorder(replay_id, channel, args.buffer_size)
    visited = {maze.entry}
    history = simulated_history(replay_id, route, args.ticks)

    async with Group() as group:
        group << writer.run()
        for frame in history.frames:
            await recorder.on_frame(frame)
            position = (int(frame.player.position.x), int(frame.player.position.y))
            if position not in visited:
                visited.add(position)
                recorder.on_collectible_change(
                    CollectibleChange(
                        frame.tick,
                        TileIndex(position[1] * maze.width + position[0]),
                        Collectible.NONE,
                    )
                )

        await recorder.finish()
        await channel.close()

    last_tick = Tick(args.ticks - 1)
    snapshot = store.snapshot(replay_id, last_tick).unwrap()
    assert snapshot.tick == last_tick
    assert snapshot.phase is GamePhase.DYING
    assert snapshot.ghosts == history.frames[-1].ghosts
    assert all(store.frame(replay_id, frame.tick).unwrap() == frame for frame in history.frames)
    assert store.replay(replay_id).unwrap().ended_at is not None
    print("\n== simulated game ==")
    print(f"maze:         {maze.width}x{maze.height}, seed {args.seed}")
    print(f"path:         {len(path)} tiles")
    print(f"frames:       {args.ticks:,}")
    print("ghosts:       Blinky, Pinky, Inky, Clyde")
    print("events:       frightened -> Inky eaten -> Blinky collision -> DYING")
    print(f"batches:      {(args.ticks + args.buffer_size - 1) // args.buffer_size:,}")
    print(f"visited:      {len(visited):,} tiles")
    print(f"database:     {database_size(DB_PATH) / 1_048_576:.2f} MiB")
    print("verified:     final snapshot and finished metadata")
    return 0


def run(args: ReplayArgs) -> int:
    """Exercise the selected portion of the ReplayStore API.

    Args:
        args: Selected integration case and stress-test controls.

    Returns:
        Zero when the selected replay exercise succeeds.
    """
    remove_database(DB_PATH)

    store = ReplayStore(DB_PATH)

    print("== initialize ==")

    store.initialize_replay().unwrap()

    print("OK")

    if args.case == "simulate":
        result = asyncio.run(simulate_game(store, args))
        if not args.keep_db:
            remove_database(DB_PATH)
        return result

    print("\n== create maze ==")

    maze = EncodedMaze(
        width=2,
        height=2,
        entry=(0, 0),
        exit=(1, 1),
        topology=b"\x12\x34",
        initial_collectibles=b"\x55",
        checksum=b"test-checksum",
    )

    maze_id = store.create_maze(maze).unwrap()

    print(f"created maze: {maze_id}")

    print("\n== load maze ==")

    loaded_maze = store.maze(maze_id).unwrap()

    assert loaded_maze == maze

    print("maze roundtrip OK")

    if args.case == "maze":
        return 0

    print("\n== create replay ==")

    replay_id = store.create_replay(
        maze_id=maze_id,
        tick_hz=60,
        level=1,
        simulation_version=1,
        config_hash=b"test-config",
        rng_seed=42,
    ).unwrap()

    print(f"created replay: {replay_id}")

    print("\n== load replay ==")

    replay = store.replay(replay_id).unwrap()

    assert replay.id == replay_id
    assert replay.maze_id == maze_id
    assert replay.ended_at is None
    assert replay.tick_hz == 60
    assert replay.level == 1
    assert replay.simulation_version == 1
    assert replay.config_hash == b"test-config"
    assert replay.rng_seed == 42

    print("replay roundtrip OK")

    if args.case == "metadata":
        return 0

    if args.case == "stress":
        result = stress(store, replay_id, args)
        if not args.keep_db:
            remove_database(DB_PATH)
        return result

    if args.case == "death":
        batch = death_scenario(args.scenario, replay_id)
        store.append(batch).unwrap()
        loaded = tuple(store.frame(replay_id, frame.tick).unwrap() for frame in batch.frames)
        assert loaded == batch.frames

        print("\n== death scenario ==")
        print(f"scenario:     {args.scenario}")
        print(f"frames:       {len(batch.frames)}")
        for frame in loaded:
            ghosts = ", ".join(
                f"{ghost.ghost.name}@({ghost.position.x},{ghost.position.y})/{ghost.state.name}"
                for ghost in frame.ghosts
            )
            pac = frame.player.position
            print(
                f"tick {frame.tick}: pac=({pac.x},{pac.y})/",
                frame.player.direction.name,
                f" ghosts=[{ghosts}] phase={frame.phase.name}",
                sep="",
            )
        print("verified:     FrameBatch persisted and reconstructed")
        if not args.keep_db:
            remove_database(DB_PATH)
        return 0

    print("\n== append frame batch ==")

    frame = replay_frame(0)

    change = CollectibleChange(
        tick=Tick(0),
        tile=TileIndex(0),
        collectible=Collectible.PACGUM,
    )

    batch = FrameBatch(
        replay_id=replay_id,
        frames=(frame,),
        collectible_changes=(change,),
    )

    store.append(batch).unwrap()

    print("batch append OK")

    print("\n== load frame ==")

    loaded_frame = store.frame(
        replay_id,
        Tick(0),
    ).unwrap()

    assert loaded_frame == frame

    print("frame roundtrip OK")

    print("\n== snapshot ==")

    snapshot = store.snapshot(
        replay_id,
        Tick(0),
    ).unwrap()

    assert snapshot.replay_id == replay_id
    assert snapshot.tick == Tick(0)
    assert snapshot.player == frame.player
    assert snapshot.ghosts == frame.ghosts
    assert snapshot.score == frame.score
    assert snapshot.lives == frame.lives
    assert snapshot.phase == frame.phase

    print("snapshot reconstruction OK")

    if args.case == "frames":
        return 0

    print("\n== finish replay ==")

    store.finish(replay_id).unwrap()

    finished = store.replay(replay_id).unwrap()

    assert finished.ended_at is not None

    print("finish OK")

    print("\n== all tests passed ==")
    print(f"database: {DB_PATH}")
    return 0


def main() -> None:
    """Select and run a replay integration case.

    Raises:
        SystemExit: With the selected exercise status.
    """
    command = Command(
        name="replay-test",
        short="Exercise replay persistence and storage costs",
        long="Run quick replay checks or write a large replay in bounded batches",
        example=(
            "uv run python delete_me/replay/main.py --case stress "
            "--frames 1000000 --batch_size 10000"
        ),
        schema=ReplayArgs,
        run=run,
    )
    result = command.execute(sys.argv[1:])
    if isinstance(result, Err):
        result.print_diagnostic()
        raise SystemExit(2)
    raise SystemExit(cast(int, result.value))


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, Exception) as error:
        print(f"replay-test failed unexpectedly: {error}")
        raise SystemExit(1) from None
