"""Pac-Man's default teammate onboarding and help guide.

Run this file with ``uv run python example.py``. It is deliberately independent
from the unfinished game modules: copy the small patterns into a real feature,
then replace the fake inputs with config, board, pygame, or storage values.

Rule of thumb:

* ``Result[T, E]`` means an operation may fail and the caller needs its reason.
* ``Option[T]`` means absence is normal and has no error to report.
* ``@pipe`` makes simple one-input transformations read left to right.
* ``defer`` / ``@deferred`` own LIFO cleanup for a scope.
* ``match_`` chooses the first fitting shape, type, or typed-errs variant.
* ``Group`` and ``Channel[T]`` make related async work explicit and scoped.

Generated by Codex with Veya's direction. Keep this guide small, runnable, and
independent from unfinished game modules.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass

from cli_fw import CliError
from python_crimes import (
    REST,
    DeferStack,
    attr,
    capture,
    defer,
    deferred,
    ge,
    gt,
    match_,
    matcher,
    pipe,
    terminate,
    type_,
)
from typed_concurrency import Channel, Group
from typed_errs import Err, Nothing, Ok, Option, Result, Some, catch_bubble


def heading(title: str) -> None:
    """Print a readable section boundary for the walkthrough."""
    print(f"\n=== {title} ===")


# Pipes are for a transformation where each step consumes exactly the last
# step's value. Use ordinary function calls when the data flow is not linear.
@pipe
def trim_command(raw: str) -> str:
    """Normalize console input before command dispatch.

    Returns:
        A lowercase command without surrounding whitespace.
    """
    return raw.strip().lower()


@pipe
def command_words(command: str) -> list[str]:
    """Turn one normalized command into tokens.

    Returns:
        Whitespace-separated command tokens.
    """
    return command.split()


def demonstrate_pipes() -> None:
    """Show the left-to-right pipeline syntax."""
    heading("Pipes: one value through simple transformations")
    words = "  PAUSE   NOW  " @ trim_command @ command_words
    print(words)  # ['pause', 'now']


# Option is for expected absence: a board may simply not contain a power
# pellet.
def power_pellet_at(tile: tuple[int, int]) -> Option[str]:
    """Return an optional board item; no pellet is not an error."""
    return Some("power pellet") if tile == (3, 4) else Nothing()


# Result is for failure with a reason: bad score input must be reported to the
# caller instead of being silently confused with an absent value.
def parse_score(raw: str) -> Result[int, CliError]:
    """Parse a positive score-like value from a fake input source.

    Returns:
        Ok with the score, or Err when the input is not a non-negative integer.
    """
    if not raw.isdigit():
        return Err(CliError.INVALID_ARGUMENT_TYPE)
    score = int(raw)
    return Ok(score) if score >= 0 else Err(CliError.INVALID_ARGUMENT_TYPE)


def demonstrate_result_and_option() -> None:
    """Show conventional branching before using matcher sugar."""
    heading("Result and Option: failure versus normal absence")
    pellet = power_pellet_at((0, 0))
    score = parse_score("1200")

    if isinstance(pellet, Some):
        print(f"Board contains {pellet.value}")
    else:
        print("No power pellet here: this is normal")

    if isinstance(score, Ok):
        print(f"Score loaded: {score.value}")
    else:
        print(f"Score input failed: {score.error.name}")


def demonstrate_defer() -> None:
    """Show explicit scope cleanup, useful around callback-style resources."""
    heading("defer: LIFO cleanup owned by this scope")
    events: list[str] = []
    with defer() as cleanup:
        cleanup << (lambda: events.append("close replay file"))
        cleanup << (lambda: events.append("release audio channel"))
        events.append("play level")
    print(events)  # cleanup runs in reverse registration order.


@catch_bubble
@deferred
def load_player_name(
    cleanup: DeferStack,
    found: bool,
) -> Result[str, CliError]:
    """Use @deferred with .q; cleanup runs even when Err bubbles out.

    Returns:
        Ok with the player name, or Err when it could not be loaded.
    """
    events: list[str] = []

    def writer(chunk: str | None) -> None:
        if chunk is None:
            print("writer closed by deferred cleanup")
        else:
            events.append(chunk)

    cleanup << terminate(writer)
    player_name = (
        Ok("Pac-Man") if found else Err(CliError.MISSING_ARGUMENT_VALUE)
    )
    name: str = player_name.q
    writer(f"loaded {name}")
    print(events)
    return Ok(name)


def demonstrate_deferred() -> None:
    """Show decorator-style cleanup for a whole helper function."""
    heading("@deferred: cleanup without another indentation level")
    print(load_player_name(True))
    print(load_player_name(False))


@dataclass(frozen=True)
class Ghost:
    """Small event payload for attribute-pattern examples."""

    name: str
    frightened: bool
    speed: int


Event = dict[str, object]


def demonstrate_match_with_block(event: Event) -> str:
    """Use a with-block when a decision has several visually distinct arms.

    Returns:
        The label emitted by the first matching event pattern.
    """
    with match_(event) as cases:
        # Mapping/list patterns are recursive. capture() determines handler
        # arguments in traversal order.
        cases.case({"kind": "pellet", "points": capture(int) & gt(0)}) << (
            lambda points: f"add {points} points"
        )
        cases.case({"kind": "input", "keys": ["up", str, REST]}) << "move up"
        cases.case(
            {
                "kind": "ghost",
                "ghost": (
                    type_(Ghost)
                    & attr("name", capture(str))
                    & attr("frightened", True)
                ),
            }
        ) << (lambda name: f"ghost {name}: run")
        cases.default << "ignore event"
    return cases.value


def demonstrate_match_styles() -> None:
    """Show block matching, fluent matching, and typed-errs arms."""
    heading("match_: shapes, guards, captures, Result, and Option")
    print(demonstrate_match_with_block({"kind": "pellet", "points": 50}))
    print(
        demonstrate_match_with_block({"kind": "input", "keys": ["up", "held"]})
    )

    # Fluent matching uses the exact same engine. Prefer it for a compact
    # return expression; use the with form above for a longer decision tree.
    label = (
        match_("level:3")
        .case(type_(int))
        .when(ge(1))
        .then(lambda level: f"level {level}")
        .regex(r"level:(\d+)")
        .then(lambda level: f"level {level}")
        .default.then("invalid level")
        .value
    )
    print(label)

    # typed-errs variants are first-class pattern arms. Handlers receive the
    # inner payload, not the Ok/Err/Some wrapper.
    with match_(parse_score("not a number")) as cases:
        cases.ok << (lambda value: f"score is {value}")
        cases.err << (lambda error: f"show input error: {error.name}")
    print(cases.value)

    with match_(power_pellet_at((3, 4))) as cases:
        cases.some << (lambda item: f"eat {item}")
        cases.nothing << "keep moving"
    print(cases.value)


def demonstrate_reusable_dispatch() -> None:
    """Build once, then use the same classification for every score."""
    heading("matcher(): reusable dispatch for repeated classifications")
    classify_score = (
        matcher()
        .case(0)
        .then("new game")
        .case(type_(int) & ge(10_000))
        .then("extra-life territory")
        .case(type_(int) & gt(0))
        .then("keep playing")
        .default.then("invalid score")
    )
    for score in (0, 250, 12_000, "oops"):
        print(f"{score!r} -> {score @ classify_score}")


async def demonstrate_typed_concurrency() -> None:
    """Show structured producer/consumer work without game-module coupling."""
    heading("typed-concurrency: scoped tasks and channels")
    events = Channel[str](2)

    async def produce() -> None:
        """Publish a few pretend game events before normal closure."""
        for event in ("ready", "pellet", "level complete"):
            await events.send(event)
        await events.close()

    async def consume() -> None:
        """Handle events until the producer closes its channel."""
        async for event in events:
            print(f"event: {event}")

    async with Group() as group:
        _ = group << produce()
        _ = group << consume()


def main() -> None:
    """Run the teammate-oriented tour."""
    demonstrate_pipes()
    demonstrate_result_and_option()
    demonstrate_defer()
    demonstrate_deferred()
    demonstrate_match_styles()
    demonstrate_reusable_dispatch()
    asyncio.run(demonstrate_typed_concurrency())


if __name__ == "__main__":
    main()
